FROM node:22.5.0-bookworm-slim

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY ./server ./server

RUN npm install -g typescript

RUN npx tsc -p ./server/tsconfig.json

EXPOSE 5000

CMD ["node", "server/dist/index.js"]
